// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW067iCfEz4XNzA3O4MfLLGLTTk48W39g',
    appId: '1:88088570075:web:5e0847226b14a62f6ac4fe',
    messagingSenderId: '88088570075',
    projectId: 'keypocket-da8ee',
    authDomain: 'keypocket-da8ee.firebaseapp.com',
    storageBucket: 'keypocket-da8ee.firebasestorage.app',
    measurementId: 'G-7MTCYSMLJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcbtXKz8Hv4umIOsJDWElqPX3wfpwYQHY',
    appId: '1:88088570075:android:13ae90a03190f4a56ac4fe',
    messagingSenderId: '88088570075',
    projectId: 'keypocket-da8ee',
    storageBucket: 'keypocket-da8ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFX3HIOcO4U05fAGTUUyUYYfaGRNlL468',
    appId: '1:88088570075:ios:1d5764a0d034fea76ac4fe',
    messagingSenderId: '88088570075',
    projectId: 'keypocket-da8ee',
    storageBucket: 'keypocket-da8ee.firebasestorage.app',
    iosBundleId: 'com.example.keypocket1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFX3HIOcO4U05fAGTUUyUYYfaGRNlL468',
    appId: '1:88088570075:ios:1d5764a0d034fea76ac4fe',
    messagingSenderId: '88088570075',
    projectId: 'keypocket-da8ee',
    storageBucket: 'keypocket-da8ee.firebasestorage.app',
    iosBundleId: 'com.example.keypocket1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW067iCfEz4XNzA3O4MfLLGLTTk48W39g',
    appId: '1:88088570075:web:019c9ee2d0b230866ac4fe',
    messagingSenderId: '88088570075',
    projectId: 'keypocket-da8ee',
    authDomain: 'keypocket-da8ee.firebaseapp.com',
    storageBucket: 'keypocket-da8ee.firebasestorage.app',
    measurementId: 'G-T8KXXCZ3YD',
  );

}